# Generated by Django 5.1.2 on 2024-10-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentRegistraytion',
            new_name='Student',
        ),
    ]
